### ISSUE TITLE
How to see counters mapping to my exposed endpoints

### ISSUE THREAD

**Issue by priscofarina** [open-telemetry/opentelemetry-js-contrib#1359] opened 2023-01-19 11:05 UTC
Hi guys,
 is there any way to instrument the code in order to automatically fetch the counters mapping to the endpoints of my application?

Below the counters automatically created but I would like to get if there is a way to have information about the endpoint of that.

```
const prometheusExporter = new PrometheusExporter(
    { preventServerStart: true },
    () => { console.log(`>>>> Prometheus scrape endpoint: http://localhost:${pPort}${pEndpoint}`); }
);

const sdk = new opentelemetry.NodeSDK({
    // Note that you can add the resource automatically by setting the environment variable OTEL_RESOURCE_ATTRIBUTES=
    // "service.name=echo-server,service.namespace=tutorial,service.version=1.0,service.instance.id=`uuidgen`,host.name=${HOSTNAME:},host.type=`uname -m`,os.name=`uname -s`,os.version=`uname -r`"
    // Here are the minimum set to identify a ghost microservice
    // Values are hardcoder, however they must be taken from the
    // environment variables. We should have env vars for service name, version, region, etc.
    // This iformation let use discover the metrics related to a specific service in Sysdig/Prometheus ui
    //
    resource: new Resource({
      [SemanticResourceAttributes.SERVICE_NAME]: 'echo-server',
      [SemanticResourceAttributes.SERVICE_NAMESPACE]: 'service-name',
      [SemanticResourceAttributes.SERVICE_VERSION]: 'service-version'
      [SemanticResourceAttributes.DEPLOYMENT_ENVIRONMENT]: 'environment',
      'deployment.region': 'region'
    }),
```

    // Optional - If omitted, the metrics SDK will not be initialized
    metricReader: prometheusExporter,

    // Optional - you can use the metapackage or load each instrumentation individually
    instrumentations: [getNodeAutoInstrumentations()],

    // See the Configuration section below for additional  configuration options
});

For example if my application exposes two endpoints I would like to get the information for endpoint about the http return codes, since right now it is a collection without doing differences within the different endopoints.

```
/endpoin1
/endpoint2
```

so I wonder if it is possible doing that automatically.

```
http_server_duration_count{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464"} 1 1674123257494
http_server_duration_sum{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464"} 15 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="0"} 0 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="5"} 0 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="10"} 0 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="25"} 1 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="50"} 1 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="75"} 1 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="100"} 1 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="250"} 1 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="500"} 1 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="1000"} 1 1674123257494
http_server_duration_bucket{http_scheme="http",http_method="GET",net_host_name="localhost",http_flavor="1.1",http_status_code="200",net_host_port="9464",le="+Inf"} 1 1674123257494
# HELP http_client_duration measures the duration of the outbound HTTP requests
# UNIT http_client_duration ms
# TYPE http_client_duration histogram
```

package.json:

```
{
  "name": "open-telemetry",
  "version": "1.0.0",
  "description": "",
  "main": "monitoring.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@opentelemetry/api": "^1.4.0",
    "@opentelemetry/auto-instrumentations-node": "^0.36.0",
    "@opentelemetry/exporter-prometheus": "^0.35.0",
    "@opentelemetry/sdk-node": "^0.35.0",
    "express": "^4.18.2"
  }
}
```

**Comment by dyladan** [comment] 2023-01-25 17:24
This is a duplicate of the issue in the main repo https://github.com/open-telemetry/opentelemetry-js/issues/3563

Please do not open multiple issues for the same question

**Closed by dyladan** 2023-01-25 17:24 UTC
Labels: bug
