### ISSUE TITLE
pg instrumentation crashes when using ES module.

### ISSUE THREAD

**Issue by nlindley** [open-telemetry/opentelemetry-js-contrib#1588] opened 2023-07-14 15:52 UTC
### What version of OpenTelemetry are you using?

- @opentelemetry/api: 1.4.1
- @opentelemetry/instrumentation: 0.41.0
- @opentelemetry/instrumentation-pg: 0.36.0
- @opentelemetry/sdk-node: 0.41.0
- @opentelemetry/sdk-trace-base: 1.15.0

### What version of Node are you using?

18.16.1

### What did you do?

Attempted to instrument pg using the default import.

### What did you expect to see?

The app to start.

### What did you see instead?

The application crashes on import of the module.

### Additional context

We have minimal reproductions of the issue: https://github.com/nlindley/otel-esm-examples/tree/master/pg

**Comment by dyladan** [comment] 2023-07-19 16:37
I think this is the same as https://github.com/open-telemetry/opentelemetry-js/issues/3976

For now you may be able to just use the previous version until we can provide a fix.

**Comment by klippx** [comment] 2023-07-24 15:56
Duplicate of #1587

**Closed** 2023-10-17 10:59 UTC
Labels: bug, priority:p1
