### ISSUE TITLE
not able to disable resource detector

### ISSUE THREAD

**Issue by droger88** [open-telemetry/opentelemetry-js-contrib#1780] opened 2023-11-01 20:59 UTC
## Steps to Reproduce
1. enable auto instrument on k8s
```
 annotations:
        # enable opentelemetry auto-instrument
        instrumentation.opentelemetry.io/inject-nodejs: "my-instrument"
```
2. enable only `env` for resource detector using environment variable
```
...
      containers:
        - name: app
          image: app-image
          envFrom:
            - configMapRef:
                name: my-config
          env:
          - name: OTEL_SERVICE_NAME
            value: my-app
          - name: OTEL_NODE_RESOURCE_DETECTORS
            value: "env"
...
```
3. enable http logs in the application, and I can see it tries to get meta data for gcp and alibaba cloud.
```
HTTP 29: SOCKET ERROR: ECS metadata api request timed out. Error: ECS metadata api request timed out.
    at Timeout._onTimeout (/otel-auto-instrumentation/node_modules/@opentelemetry/resource-detector-alibaba-cloud/build/src/detectors/AlibabaCloudEcsDetector.js:87:29)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

```
HTTP 1: SOCKET ERROR: getaddrinfo ENOTFOUND metadata.google.internal. Error: getaddrinfo ENOTFOUND metadata.google.internal.
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
```
4. we also see some errors when the init container starts, not sure if this will be a problem as well, we are running container as non-root
```
...
cp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/dist/protobuf.min.js': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/dist/protobuf.min.js.map': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/dist': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/ext/debug/README.md': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/ext/debug/index.js': Operation not permittedcp: can't preserve ownership of '/otel-auto-instrumentation/./node_modules/protobufjs/ext/debug': Operation not permitted
...
```
## Expected Result
auto instrument should not try to get meta data for google or alibaba cloud
## Actual Result
it tries to query the infra meta data which does not exist
## Additional Details
image version: `otel/autoinstrumentation-nodejs:0.44.0`

**Comment by pichlermarc** [comment] 2023-11-08 15:21
Yes, I can see that this is a pain if the auto-instrumentation is used in this way. 🤔 

However, I'm removing the bug label and adding `enhancement` as this is not a feature that already exists and is broken but a request for a feature that is currently not implemented. I'd definetly be useful to have though, so I'd be happy to see a contribution in this repo that allows for allow-listing resource detectors, adding `up-for-grabs` 🙂

**Comment by illrill** [comment] 2024-02-14 08:19
Same situation here. I'm sorry @pichlermarc but I didn't quite understand why this would be a feature and not a bug - could you elaborate? The README says we can use `OTEL_NODE_RESOURCE_DETECTORS` to enable only certain resource detectors.

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/metapackages/auto-instrumentations-node/README.md#usage-auto-instrumentation

**Comment by pichlermarc** [comment] 2024-02-14 13:00
@illrill thanks for asking. To be honest I don't fully remember my what my train of through was back then. Looks to me like I  made a mistake. Sorry about that.

This should work - are you also using the operator? Looking at the code, [they set the resource detectors directly when instantiating NodeSDK](https://github.com/open-telemetry/opentelemetry-operator/blob/main/autoinstrumentation/nodejs/src/autoinstrumentation.ts), so that would looks to me like it should be filed in the operator repo: https://github.com/open-telemetry/opentelemetry-operator 

If you're using it like `node --require '@opentelemetry/auto-instrumentations-node/register' ` and it's not working then this repo here is actually the correct place to report the bug. The same is true for `getResourceDetectorsFromEnv()`. If this is what you're using and it's not working then this also belongs here.

**Comment by illrill** [comment] 2024-02-14 15:08
@pichlermarc Thank you for the reply and guidance. You definitely nailed it, I'm using the auto-injection feature of the Operator (looks like @droger88 is also doing so). I've opened an issue in that repo instead 👍

**Comment by pichlermarc** [comment] 2024-02-14 15:28
> @pichlermarc Thank you for the reply and guidance. You definitely nailed it, I'm using the auto-injection feature of the Operator (looks like @droger88 is also doing so). I've opened an issue in that repo instead 👍

Thanks for following up. I'll close the issue right here as the one over at the operator repo can be used for further tracking. :+1:

**Closed by pichlermarc** 2024-02-14 15:28 UTC
Labels: enhancement, up-for-grabs, pkg:auto-instrumentations-node
