### ISSUE TITLE
Support mongodb v5

### ISSUE THREAD

**Issue by samimusallam** [open-telemetry/opentelemetry-js-contrib#1389] opened 2023-02-12 12:33 UTC
mongodb instrumentation has support for version range >=3.3 to 4.*

The package released a new major version [5.0.1](https://www.npmjs.com/package/mongodb/v/5.0.1) which is not supported, and we should update the instrumentation to support it.

The renovate bot opened a PR to bump the instrumentation version to 5.0.1: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1388

**Comment by blumamir** [comment] 2023-02-12 12:36
Thanks!
duplicate of https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1373

**Closed by blumamir** 2023-02-12 12:36 UTC
