### ISSUE TITLE
Express instrumentation results in routes with no stack, crashing Ghost

### ISSUE THREAD

**Issue by Zirak** [open-telemetry/opentelemetry-js-contrib#2271] opened 2024-06-08 22:03 UTC
## Steps to Reproduce

Given the following `index.js`, which imitates [Ghost's](https://github.com/TryGhost/Ghost) routing:

```js
const http = require('http');
const express = require('express');

// https://github.com/TryGhost/Ghost/blob/fefb9ec395df8695d06442b6ecd3130dae374d94/ghost/core/core/frontend/web/site.js#L31
let router;
const SiteRouter = (req, res, next) => router(req, res, next);
function setupSiteApp() {
    const siteApp = express('site');

    // fascimile of ParentRouter
    router = express.Router();
    router.use('/:slug', (_1, _2, next) => {
        console.log('application code - I will never trigger');
        next()
    });
    router.param('slug', triggerBug);

    Object.setPrototypeOf(SiteRouter, router)
    siteApp.use(SiteRouter);

    return siteApp;
}

// this is the bug-inducing function, ParentRouter#_respectDominantRouter
function triggerBug(req, res, next, slug) {
    // ParentRouter#getSiteRouter
    const siteRouter = req.app._router.stack.find((router) => {
        return router.name === 'SiteRouter';
    });

    console.log('stack:', siteRouter.handle.stack);
    // this should throw
    siteRouter.handle.stack.every;
    // ...and app code will never trigger
    next();
}

// now that setup is done, try to trigger the bug
const app = setupSiteApp();
app.listen(5000, () => {
    console.log('listening');
    http.get('http://localhost:5000/foo', (res) => {
        res.resume();
    });
});

```

Run twice:

```sh
# without otel
node index.js
# with otel
env NODE_OPTIONS='--require @opentelemetry/auto-instrumentations-node/register' node index.js
```

## Expected Result

Both runs print a router stack like:

```
❯ node index.js
listening
stack: [
  Layer {
    handle: [Function (anonymous)],
    name: '<anonymous>',
    params: { slug: 'foo' },
    path: '/foo',
    keys: [ [Object] ],
    regexp: /^\/(?:([^\/]+?))\/?(?=\/|$)/i {
      fast_star: false,
      fast_slash: false
    },
    route: undefined
  }
]
```

## Actual Result

When running with otel, the router is `undefined`, causing shenanigans and a server 500:

```
❯ env NODE_OPTIONS='--require @opentelemetry/auto-instrumentations-node/register' OTEL_LOG_LEVEL=none node index.js
listening
stack: undefined
TypeError: Cannot read property 'every' of undefined
    at triggerBug (/home/zirak/work/ghost-every-siterouter-bug/index.js:33:29)
    at paramCallback (/home/zirak/work/ghost-every-siterouter-bug/node_modules/express/lib/router/index.js:415:7)
    at param (/home/zirak/work/ghost-every-siterouter-bug/node_modules/express/lib/router/index.js:395:5)
    at Function.process_params (/home/zirak/work/ghost-every-siterouter-bug/node_modules/express/lib/router/index.js:421:3)
    at next (/home/zirak/work/ghost-every-siterouter-bug/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/zirak/work/ghost-every-siterouter-bug/node_modules/express/lib/router/index.js:175:3)
    at router (/home/zirak/work/ghost-every-siterouter-bug/node_modules/express/lib/router/index.js:47:12)
    at SiteRouter (/home/zirak/work/ghost-every-siterouter-bug/index.js:6:40)
    at /home/zirak/work/ghost-every-siterouter-bug/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:214:37
    at Layer.handle [as handle_request] (/home/zirak/work/ghost-every-siterouter-bug/node_modules/express/lib/router/layer.js:95:5)
```

## Additional Details

It's also possible to replicate this with Ghost itself. Running Ghost with opentelemetry and visiting http://localhost:2368/about/ results in a 500.

I've yet to successfully debug exactly where this originates.

**Comment by pichlermarc** [comment] 2024-06-10 11:10
@JamieDanielson would you mind taking a look at this? :slightly_smiling_face:

**Comment by JamieDanielson** [comment] 2024-06-10 13:52
At a glance, this seems like it will be resolved with the changes in #2137 , which was created to fix #1950 . The short description includes this note: "The patched function now exposes same properties proxying the ones from the original handle function." This update will be available in the [next release](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2263).

**Comment by JamieDanielson** [comment] 2024-06-10 14:38
Hmm... actually I'm testing out the changes and it doesn't seem to resolve this issue. When running this repro app in debug mode, I can see the stack on `siteRouter.handle` Prototype. When running in debug mode with the auto-instrumentations register command, that stack is still missing... but as mentioned above, it does exist on `__original`. This will need a PR, and I am also curious if this bit of detail may be necessary for the initial fix to fully work in its intended scenario as well.

@Zirak thank you again for the detailed report and reproducer. If you are open to it, a PR would be appreciated on this one!

**Comment by JamieDanielson** [comment] 2024-06-10 14:56
> If you are open to it, a PR would be appreciated on this one!

In some local testing I was able to add `Object.setPrototypeOf(patched, original);` right after the `Object.keys(original).forEach...` and before the new `return patched;` 

```js
            Object.keys(original).forEach(key => {
                Object.defineProperty(patched, key, {
                    get() {
                        return original[key];
                    },
                    set(value) {
                        original[key] = value;
                    },
                });
            });
            Object.setPrototypeOf(patched, original);
            return patched;
```

**Comment by Zirak** [comment] 2024-06-12 13:12
Thanks for the follow-up, and talk about timing with the ongoing express patch!

Since it was released I able to install @opentelemetry/instrumentation-express@0.40.1 and reproduce that the bug is still happening. After some debugging I think I understand why: These properties are not `original`'s *own* properties, they belong to its prototype. Putting a conditional breakpoint in the newer `Object.keys(original)...` line (I put a conditional breakpoint on `original.stack`), we can see:

```js
> original.stack
[Layer]

> Object.keys(original)
[]

> original.hasOwnProperty('stack')
false

> Object.getPrototypeOf(original).hasOwnProperty('stack')
true

> Object.keys(Object.getPrototypeOf(original))
['params', '_params', 'caseSensitive', 'mergeParams', 'strict', 'stack']
```

Express internals confuse me all the way to the 7th circle, so there might be flows in which these keys do exist on `original` and not on its prototype - I'm not 100% sure when, since I couldn't reproduce them in local testing. @david-luna when you wrote #2137 were you able to reproduce "outside of the lab"? I'm curious what flows reach this behaviour.

The reason my (naive) `setPrototypeOf` works is that it wholesale defers all getters to the prototype. As @david-luna correctly [points out in the patch PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2137#issuecomment-2071711540), this isn't ideal since it doesn't defer setters.

Seeing the above, I have three suggestions in mind:
1. Use inheritance and leave setters to be a future problem (nothing can possibly go wrong, right?)
2. Copy keys from the `origin` prototype in addition to `origin`
3. Instead of returning a normal wrapped function, return a Proxy which defers getters/setters to `original`, and `apply` to `wrapped`

3 is I think most "pure" solution, in that it emulates existing behaviour, but comes with two tradeoffs:
1. Proxies are slower than regular objects (could be better since I last benchmarked a bazillion years ago)
2. I have no idea how this will behave in the larger SDK, like unwrapping

**Comment by david-luna** [comment] 2024-06-20 11:06
@Zirak @JamieDanielson 

OTEL's handler patching occurs when `siteApp.use(SiteRouter);` is being called. So it is patching an object which has no `stack` property on its own but in the prototype. So in #2137 there is the wrong assumption that a handler will have its properties as own and used `Object.keys` to iterate over them.

So here's my 2cts on the options:

1. with inheritance we have the properties available but we will have a similar situation as described in [this comment](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2137#discussion_r1626178337) when discussing between `Object.defineProperty` and copy
2. copying properties is similar to 1 (check the linked comment). Also in this scenario all props were moved to the prototype but noting prevents another lib to do the same and move the properties even further in the prototype chain. We could walk up the chain to gather all properties on use [for..in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)
3. I agree is a good fit. Regarding perf the I think the `use` API is for adding middlewares before starting the app so if there is a perf impact that would be at startup time

> I have no idea how this will behave in the larger SDK, like unwrapping

This is a good question. When unwrapping the handlers are still the patched ones. I wonder if we should keep track of them ti patch/unpatch accordingly 🤔

**Comment by david-luna** [comment] 2024-06-20 14:50
Note: To get a callable function with the tracing logic we need to create the proxy using the patched function as target

```js
const patched = funtcion (req, res) { ... }; 

return new Proxy(patched, {
  get (target, prop) { return original[prop]; },
  set (target, prop, val) { original[prop] = val; },
});
```

otherwise the returned function would have no tracing logic at all.

**Closed** 2024-07-09 23:07 UTC
Labels: bug, priority:p1, pkg:instrumentation-express, has:reproducer
