### ISSUE TITLE
@opentelemetry/instrumentation-fs` fails to wrap fs promises

### ISSUE THREAD

**Issue by weyert** [open-telemetry/opentelemetry-js-contrib#1305] opened 2022-11-25 23:43 UTC
### What version of Node are you using?
18.12.1

### What did you do?
I installed Opentelemetry and use the auto-instrumentation meta package via `node-sdk` to instrument my node backend application but when starting up the application thrown a runtime error

### What did you expect to see?
Successfully running my backend application without throwing errors

### What did you see instead?
```
/Users/xxxx/node_modules/@opentelemetry/instrumentation-fs/build/src/instrumentation.js:53
                        if (instrumentation_1.isWrapped(fs.promises[fName])) {
                                                                   ^

TypeError: Cannot read properties of undefined (reading 'access')
    at InstrumentationNodeModuleDefinition.patch (/Users/xxxx/node_modules/@opentelemetry/instrumentation-fs/build/src/instrumentation.js:53:68)
```

Looks like the `fs.promises` is undefined in my case which causes the wrapping step to fail. I am not sure why `fs.promises` is undefined. Maybe the `supportsPromises` needs to be adapted so it also checks whether `fs.promises` is defined?

E.g. 
`const supportsPromises = parseInt(process.versions.node.split('.')[0], 10) > 8 && fs.promises`

I can't really think of a reason why `fs.promises` could be undefined. Could a library maybe override it? If so, what would be a good way to detect that in Node?

### Additional context
I am running Express

**Comment by Flarna** [comment] 2022-11-26 12:10
Which ohter modules have you loaded in your app? In special that ones loaded before the instrumentation would be insteresting.

Or can you even share a stripped down reproducer?

**Comment by bryanchriswhite** [comment] 2022-11-28 18:11
I'm experiencing what appears to be the same error in a NestJS environment. Likewise, I'm trying to use auto-instrumentations in node:

```
/app/node_modules/@opentelemetry/instrumentation-fs/build/src/instrumentation.js:53
                        if (instrumentation_1.isWrapped(fs.promises[fName])) {
                                                                   ^

TypeError: Cannot read properties of undefined (reading 'access')
    at InstrumentationNodeModuleDefinition.patch (/app/node_modules/@opentelemetry/instrumentation-fs/build/src/instrumentation.js:53:68)
    at FsInstrumentation._onRequire (/app/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:79:35)
    at /app/node_modules/@opentelemetry/instrumentation/build/src/platform/node/instrumentation.js:133:29
    at /app/node_modules/@opentelemetry/instrumentation/build/src/platform/node/RequireInTheMiddleSingleton.js:54:27
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:175:32)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/rotating-file-stream/dist/cjs/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
error Command failed with exit code 1.
```

For context, the codebase I'm attempting to add instrumentation to is now one I'm very familiar with. I had previously successfully attempted this same thing in another nestjs codebase (of similar size and complexity and with code in common) recently and did not experience this issue.

I [attempted to reproduce the issue in a new nest app](https://github.com/bryanchriswhite/open-telemetry-repro) but have been unsuccessful as of yet.

**Comment by modosc** [comment] 2022-11-28 23:09
using node 18.12.0 i see the issue with `@opentelemetry/auto-instrumentations-node@npm:^0.35.0` but reverting to `@opentelemetry/auto-instrumentations-node@npm:^0.34.0` fixes it

**Comment by bryanchriswhite** [comment] 2022-11-29 08:37
Nice one @modosc - that resolved it for me as well!

**Comment by Flarna** [comment] 2022-11-29 09:56
Created https://github.com/open-telemetry/opentelemetry-js/issues/3448 which includes a simple reproducer and some hints where the problem is located.
replacing any occurrence of `require("fs/promises")` is a workaround but most likely hard to do as this is spread across a lot npm modules.

**Comment by domharrington** [comment] 2023-01-19 10:43
This is still broken in `@opentelemetry/auto-instrumentations-node@0.36.0`. Downgrading to v0.34.0 seems to do the trick. Also seeing lots of these in the logs, which I assume are somewhat related:

```
no original function cpSync to wrap
no original function cp to wrap
no original function cp to wrap
```

**Comment by Diamondlord** [comment] 2023-02-05 18:42
I reproduced the issue in [this repository](https://github.com/Diamondlord/opentelemetry-promise-fs-issue#readme)
I hope it will help as https://github.com/open-telemetry/opentelemetry-js/pull/3451 still didn't solve the problem

**Comment by mhassan1** [comment] 2023-02-13 15:32
This should have been resolved by https://github.com/open-telemetry/opentelemetry-js/pull/3451. If you upgrade to `@opentelemetry/auto-instrumentations-node@0.36.1` or higher, you will no longer see the error.

Proper instrumentation of `fs/promises` will be addressed by https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1375.

**Comment by Diamondlord** [comment] 2023-02-13 17:15
`@opentelemetry/auto-instrumentations-node@0.36.2` is working in my case

Thanks

**Closed** 2023-02-27 06:37 UTC
Labels: bug, priority:p1
