### ISSUE TITLE
Container Detector isn't working

### ISSUE THREAD

**Issue by architgarg95** [open-telemetry/opentelemetry-js-contrib#2575] opened 2024-12-02 16:41 UTC
### What version of OpenTelemetry are you using?
"@opentelemetry/sdk-node": "0.52.0",

### What version of Node are you using?
Node 16

### What did you do?

I have a node application which is running in a Kubernetes cluster where every pod has a single container within it and every container has only one application that is running. Now ideally when getting traces I should get the container_id from the different containers that are running but that is not the case in traces and metrics both, which lead me to the conclusion of Container Resource Detector not working

### What did you expect to see?
Expected to see some container_id in the resource attributes

### What did you see instead?
no container level id to distinguish between the instances

**Comment by architgarg95** [comment] 2024-12-02 20:02
Found the cause:
        ```
let defaultDetectors = [];
        if (process.env.OTEL_NODE_RESOURCE_DETECTORS != null) {
            defaultDetectors = (0, utils_1.getResourceDetectorsFromEnv)();
        }
        else {
            defaultDetectors = [resources_1.envDetector, resources_1.processDetector, resources_1.hostDetector];
        }
        this._resourceDetectors =
            (_b = configuration.resourceDetectors) !== null && _b !== void 0 ? _b : defaultDetectors;
```

here the default resource detectors are only 3 env, process and host, the getResourceDetectorsFromEnv is only called if env variable is present which flattens the values map when all is present in the value of the env variable.

Shouldn't this behave similar when initializing programmatically, like either the user passes on a comma separated list of resource detectors or 'none' for no resource detectors and 'all' for all resource detectors to be available

**Comment by dyladan** [comment] 2024-12-04 17:47
Can you please provide your otel setup code? It sounds like you installed the detector but didn't configure it manually, and were expecting it to be automatically detected by the SDK?

The issue is that the SDK can't automatically discover detectors, and the ones that are in the contrib repo aren't "built in". Please provide your setup code so we can take a look at the usage and see if any enhancements need to be made.

**Comment by dyladan** [comment] 2024-12-04 17:47
I'm going to leave the triage label on this for now, but I don't think this is a bug as much as it is just unexpected behavior or an enhancement request.

**Comment by architgarg95** [comment] 2024-12-04 18:11
@dyladan you are right I was expecting it to work automatically but then I passed the detector in config in the NodeSDK constructor, so working fine now

**Comment by dyladan** [comment] 2024-12-04 18:13
OK. This is a more general problem that we're aware of that affects more than just resource detectors. There are also instrumentations, propagators, span processors, et cetera. All of these pluggable interfaces can be installed, but we have no way to reliably autodetect them in node. We've discussed a few options for it, but nobody has really put in the time to make anything work. This is quite a large issue that is well out of the scope of what the original issue here was, and we're already well aware of it. 

I'm going to close this since your original issue is resolved, but the more general topic is still open to contributions if you're interested.

**Closed as completed by dyladan** 2024-12-04 18:13 UTC
Labels: bug, triage, pkg:resource-detector-container
