### ISSUE TITLE
Example code given in @opentelemetry/instrumentation-winston package not working

### ISSUE THREAD

**Issue by shivarajnaidu** [open-telemetry/opentelemetry-js-contrib#1690] opened 2023-09-20 06:39 UTC
### What version of OpenTelemetry are you using?
```
these are my deps
  "@opentelemetry/instrumentation": "^0.43.0",
   "@opentelemetry/instrumentation-winston": "^0.32.1",
   "@opentelemetry/sdk-trace-node": "^1.17.0",
   "winston": "^3.10.0"
```

### What version of Node are you using?
it is `node 20`

### What did you do?

I have tried the exact example given in readme file.
```js
const { NodeTracerProvider } = require('@opentelemetry/sdk-trace-node');
const { WinstonInstrumentation } = require('@opentelemetry/instrumentation-winston');
const { registerInstrumentations } = require('@opentelemetry/instrumentation');

const provider = new NodeTracerProvider();
provider.register();

registerInstrumentations({
  instrumentations: [
    new WinstonInstrumentation({
      // Optional hook to insert additional context to log metadata.
      // Called after trace context is injected to metadata.
      logHook: (span, record) => {
        record['resource.service.name'] = provider.resource.attributes['service.name'];
      },
    }),
    // other instrumentations
  ],
});

const winston = require('winston');
const logger = winston.createLogger({
  transports: [new winston.transports.Console()],
})
logger.info('foobar');
```

### What did you expect to see?

> {"message":"foobar","trace_id":"e21c7a95fff34e04f77c7bd518779621","span_id":"b7589a981fde09f4","trace_flags":"01", ...}

### What did you see instead?

> {"level":"info","message":"foobar"}

What is the right way to use this plugin ?

Am I missing out something here ?

**Comment by seemk** [comment] 2023-09-20 09:41
Are you using any other instrumentations? The trace context is only added if a span is active.

**Comment by trentm** [comment] 2023-09-20 18:19
If I add some lines to your script to show logging when there is an active span:

```diff
% diff -u orig.js foo.js
--- orig.js	2023-09-20 11:17:25
+++ foo.js	2023-09-20 11:17:42
@@ -23,3 +23,9 @@
   transports: [new winston.transports.Console()],
 })
 logger.info('foobar');
+
+const tracer = provider.getTracer('default');
+tracer.startActiveSpan('my-span', span => {
+    logger.info('hi in my-span');
+    span.end();
+})
```

then we can see the expected added trace-context fields (and the result of running the `logHook()`:

```
% node foo.js
{"level":"info","message":"foobar"}
{"level":"info","message":"hi in my-span","resource.service.name":"unknown_service:node","span_id":"ca6a35e2b1526177","trace_flags":"01","trace_id":"49edd66508214fe1e89bb3526784410e"}
```


So I believe the instrumentation is working as expected. However, perhaps the README could be improved to show that example.

**Comment by shivarajnaidu** [comment] 2023-09-22 03:27
A tracer instance (const tracer = provider.getTracer('default')) will have the same trace id all over the app or it will produce new one for each HTTP request (if I use logger inside express route callbacks) ?

**Comment by trentm** [comment] 2023-09-27 17:02
@shivarajnaidu 

> A tracer instance (const tracer = provider.getTracer('default')) will have the same trace id all over the app or it will produce new one for each HTTP request (if I use logger inside express route callbacks) ?

Typically that creation of an active span would be done in the instrumentation of whatever HTTP server library you are using. So if you are using:

```js
const http = require('http');

const server = http.createServer(function onRequest(req, res) {
  // ...
});
```

then the instrumentation of the `http` module will create a span (with a new trace-id, depending on an incoming `traceparent` HTTP header) for each incoming request, and that `onRequest` function will be in that span's async context. So a `log.info(...)` inside that `onRequest` function will use the span context specific to that incoming HTTP request.

**Comment by shivarajnaidu** [comment] 2023-09-28 00:39
Thanks for the reply @trentm 

Its really useful .

Thank you so much

**Closed** 2023-09-28 00:40 UTC
Labels: bug, information-requested

**Comment by coderguy1998** [comment] 2024-01-04 11:59
Hi, If I'm auto instrumenting the code using opentelemetry, wouldn't the span context be active automatically for my API calls? Because right now I'm auto instrumenting the code and logger.info still doesn't print the trace_id and span_id. It only does if I start an active span. @trentm @shivarajnaidu

**Comment by trentm** [comment] 2024-01-05 16:38
@coderguy1998 Hard to know what may be happening without specific code. Perhaps you could post a small reproduction case of what you are seeing to a new issue or to the #otel-js CNCF Slack channel (https://cloud-native.slack.com/archives/C01NL1GRPQR) so your question doesn't get lost.

**Comment by deep-iimjobs** [comment] 2024-04-19 07:34
Can somebody please look into it. [https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2119](url)
