### ISSUE TITLE
no TraceId nor SpanId with instrumentation-winston

### ISSUE THREAD

**Issue by jeromeSH26** [open-telemetry/opentelemetry-js-contrib#2512] opened 2024-10-31 16:43 UTC
### What version of OpenTelemetry are you using?
```
    "@opentelemetry/auto-instrumentations-node": "^0.52.0",
    "@opentelemetry/instrumentation": "^0.54.0",
    "@opentelemetry/instrumentation-nestjs-core": "^0.41.0",
    "@opentelemetry/instrumentation-pg": "^0.47.0",
    "@opentelemetry/instrumentation-winston": "^0.41.0",
    "@opentelemetry/resources": "^1.27.0",
    "@opentelemetry/sdk-logs": "^0.54.0",
    "@opentelemetry/sdk-metrics": "^1.27.0",
    "@opentelemetry/sdk-node": "^0.54.0",
    "@opentelemetry/sdk-trace-node": "^1.27.0",
    "@opentelemetry/semantic-conventions": "^1.27.0",
    "@opentelemetry/winston-transport": "^0.7.0",

```    
`"winston": "^3.15.0"`

### What version of Node are you using?
22.9

### What did you do?

Have applied the piece of code in the readme.md of the [winston transport repo](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/winston-transport#readme)

But both traceID or spanId are undefined

![image](https://github.com/user-attachments/assets/7a04073a-7189-4451-8945-61fd9e905e6c)

**running the program like this:**
`ts-node --require ./src/common/telemetry/tracer.ts ./src/main.ts`

**Here is the code of the tracer.ts file**

```
import { NodeTracerProvider } from '@opentelemetry/sdk-trace-node';

import { logs } from '@opentelemetry/api-logs';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
import { NestInstrumentation } from '@opentelemetry/instrumentation-nestjs-core';
import { PgInstrumentation } from '@opentelemetry/instrumentation-pg';
import { WinstonInstrumentation } from '@opentelemetry/instrumentation-winston';
import {
  ConsoleLogRecordExporter,
  LoggerProvider,
  SimpleLogRecordProcessor,
} from '@opentelemetry/sdk-logs';

const tracerProvider = new NodeTracerProvider();
tracerProvider.register();
const loggerProvider = new LoggerProvider();
loggerProvider.addLogRecordProcessor(
  new SimpleLogRecordProcessor(new ConsoleLogRecordExporter()),
);
logs.setGlobalLoggerProvider(loggerProvider);

registerInstrumentations({
  instrumentations: [
    new WinstonInstrumentation({
      enabled: true,
    }),
    new NestInstrumentation(),
    new PgInstrumentation(),
  ],
});

```
**here is the code for the  winston logger**

```
export const winstonConfig: LoggerOptions = {
  defaultMeta: { service: globalConfig().applicationName, pid: process.pid },
  handleExceptions: true,
  handleRejections: true,
  transports: [
    new OpenTelemetryTransportV3(),
    new transports.Console({
      format: format.combine(
        format.align(),
        format.splat(),
        format.timestamp(),
        format.colorize(),
        format.errors({ stack: true }),

        format.ms(),
        format.errors(),
        utilities.format.nestLike(globalConfig().applicationName, {
          colors: true,
          prettyPrint: true,
        }),
      ),
    }),
  ],
};

const logger = createLogger(winstonConfig)

```

**Comment by dyladan** [comment] 2024-11-20 18:02
Duplicate of https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2010

**Closed by dyladan** 2024-11-20 18:02 UTC
Labels: bug
