### ISSUE TITLE
@opentelemetry/instrumentation-graphql's unit test pipeline not working correctly

### ISSUE THREAD

**Issue by chigia001** [open-telemetry/opentelemetry-js-contrib#1594] opened 2023-07-17 04:29 UTC
### What version of OpenTelemetry are you using?

- @opentelemetry/instrumentation-graphql@0.35.0

### What version of Node are you using?

- \>=14 <=18

### What did you do?

- Run unit test in current repo on github action

### What did you expect to see?

- @opentelemetry/instrumentation-graphql's unit test run correctly and return list of test + code coverage report

### What did you see instead?

- @opentelemetry/instrumentation-graphql's unit test on github action run success but unable to list out list of test + only report code coverage for symbol.ts file

- pipeline: https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/5567559025/jobs/10169539286

- test output:

```
lerna info run Ran npm script 'test' in '@opentelemetry/instrumentation-graphql' in 49.4s:

> @opentelemetry/instrumentation-graphql@0.35.0 test /home/runner/work/opentelemetry-js-contrib/opentelemetry-js-contrib/plugins/node/opentelemetry-instrumentation-graphql
> nyc ts-mocha -p tsconfig.json 'test/**/*.test.ts'

------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------|---------|----------|---------|---------|-------------------
All files   |       0 |      100 |     100 |       0 |                   
 symbols.ts |       0 |      100 |     100 |       0 | 17-19             
------------|---------|----------|---------|---------|-------------------
```

- code coverage report:
https://app.codecov.io/gh/open-telemetry/opentelemetry-js-contrib/pull/1580/tree/plugins/node/opentelemetry-instrumentation-graphql/src

### Additional context
- I double check those test on local machine and unable to repproduce this behavior. There are no crash or anything.
- I able to reproduce with codespace, seem like `nyc` issue when they trying to transform code for codecoverage report. When running ts-mocha without nyc everything seem to work.

**Comment by chigia001** [comment] 2023-07-17 05:43
@haddasbronfman I think you also face similar problem with mongodb test with #1487 . I can try to update nyc, ts-mocha etc... to see if that can resolve the problem.

**Comment by haddasbronfman** [comment] 2023-07-17 09:02
@chigia001 in my case I think also the problem is because of `nyc`, although in my case I saw an empty table.

**Comment by dyladan** [comment] 2023-07-19 16:36
@chigia001 is it ok if I assign this to you since you have a PR open?

**Closed** 2023-08-10 08:41 UTC
Labels: bug, priority:p4
